// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    rules: {
      // React Native's built-in SafeAreaView is deprecated (SDK 57+).
      // Use SafeAreaView from 'react-native-safe-area-context' instead.
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "react-native",
              importNames: ["SafeAreaView"],
              message: "Use SafeAreaView from 'react-native-safe-area-context' instead.",
            },
          ],
        },
      ],
    },
  },
  {
    // Global ignores: build output and Expo-generated artifacts. `.expo/` is
    // regenerated by the Expo CLI (and gitignored) — linting generated
    // `router.d.ts` produces noise like "Unused eslint-disable directive".
    ignores: ["dist/*", ".expo/**"],
  },
  {
    // Supabase Edge Functions run on Deno, whose module system allows full
    // URL imports (e.g. `https://esm.sh/@supabase/supabase-js@2`). ESLint's
    // Node-based resolver cannot resolve URL specifiers, so
    // `import/no-unresolved` false-positives on every such import. These
    // files are excluded from `tsconfig.json` for the same reason — they are
    // Deno code, not app TypeScript — so the Node-resolution rule is scoped
    // off for this directory only. All other rules still apply.
    files: ["supabase/functions/**/*.ts"],
    rules: {
      "import/no-unresolved": "off",
    },
  },
]);
